### ISSUE TITLE
channel-flow-dg test : The hypre euclid preconditioner

### ISSUE THREAD

**Issue by jrper** [FluidityProject/fluidity#101]
While looking through a buildbot log file on one of my branches, I noticed that this test is raising a lot of PETSC errors due to calling the euclid (i.e. LU) preconditioned from hypre, which appears to no longer exist in petsc 3.6. The test still passes, so it's obviously using _something_ to solve the linear system, but it would probably be nice if this were made explicit. The test is antediluvian and owned by @dham, so I'm not sure who to ask to look at this.

**Comment by jrper** [comment]
For the record this all goes away if you switch the hypre preconditioned to boomerAMG.

**Comment by tmbgreaves** [comment]
Resolved by pull request #106
