### ISSUE TITLE
Partioning of extruded meshes incorreclty weighted

### ISSUE THREAD

**Issue by stephankramer** [FluidityProject/fluidity#114]
This was reported by @anguscr on the fluidity mailing list:

In relation to recent mailing list discussions, if you've tried having a variable number of layers in a tidal simulation, the (re-)partitioned extruded meshes can have relative sizes quite outside the Zoltan tolerance levels (eg. 4:1).

Luckily the fix is quite straightforward -- in assemble/Zoltan_callbacks.F90, go to the following lines in zoltan_cb_owned_node_count():

```
   do i = 1, count
        obj_wgts(i) =obj_wgts(i)/max_obj_wgt
   end do
```

And either delete them or comment them out. I've tested the fix, and it's given me a decent speedup (2x).

Object weighting in Zoltan doesn't need to be normalised, and the above gives you a globally (rather than locally) valid column weighting without mpi_allreduce(). I'd patch the trunk myself but I've got a proposal deadline..

**Comment by stephankramer** [comment]
This rescaling indeed does not make sense without max_obj_wgt being maximized over all processes. What I'm not entirely sure of is whether the scaling is indeed irrelevant, or whether its scale matters with respect to edge cut: i.e. if we multiply the node weights with a big number does that mean the partioner cares more about load balance and less about edge cut?

**Comment by anguscr** [comment]
It's a good question, Stephan - anecdotally, I can tell you that the 
partitions are not perfectly node-weighted, and increasing the number of 
partitions increases the differences. Nonetheless it still maintains a 
1.6-2x speedup.

Incidentally, I tried putting in an mpi_allreduce() to calculate 
max_obj_wgt, but this just hung - I suspect a blocking send/receive 
somewhere else.

Cheers
Angus



On 02/05/2016 11:11, Stephan Kramer wrote:
> This rescaling indeed does not make sense without max_obj_wgt being
> maximized over all processes. What I'm not entirely sure of is whether
> the scaling is indeed irrelevant, or whether its scale matters with
> respect to edge cut: i.e. if we multiply the node weights with a big
> number does that mean the partioner cares more about load balance and
> less about edge cut?

-- 
Dr Angus Creech

Research Fellow
Institute of Energy Systems
University of Edinburgh
Scotland

www.research.ed.ac.uk/portal/acreech2

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
