### ISSUE TITLE
Unbuilt executables in the tools directory

### ISSUE THREAD

**Issue by jrper** [FluidityProject/fluidity#117]
It's come to my attention that we have broken executables in the tools directory (I rather think I broke them). In particular these are tools not built by the fltools tools target, so they aren't tested or built under buildbot. Is there consensus whether these should be fixed, or removed, and if fixed, should they be built by `make fltools`?

Tools:

- time_average_parallel
- test_laplacian_vector

also there are the Flint_* routines, which don't seem to get compiled into an executable.

**Comment by stephankramer** [comment]
I'd say just get rid off it. Clearly nobody has missed them - and if someone does come along, we can put the effort it then to resuscitate them.
