### ISSUE TITLE
libspatialindex creates temporary files when bulk loading

### ISSUE THREAD

**Issue by jrmaddison** [FluidityProject/fluidity#119]
libspatialindex creates temporary files when bulk loading data beyond a certain size, which is quite inefficient. I'm not certain this is completely safe in parallel either, as two processes could potentially generate the same temporary filename (perhaps with very low probability) due to the use of mktemp:

```
./lib/libspatialindex.a(Tools.o): In function `Tools::TemporaryFile::TemporaryFile()':
Tools.cc:(.text+0x34ac): warning: the use of `mktemp' is dangerous, better use `mkstemp'
```

The following edit disables the use of disk caching by the libspatialindex bulk loader in a minimally invasive way:

```
index 50427ee..66de5fa 100644
--- a/spatialindex-1.8.0/src/rtree/RTree.cc
+++ b/spatialindex-1.8.0/src/rtree/RTree.cc
@@ -207,7 +207,7 @@ SpatialIndex::ISpatialIndex* SpatialIndex::RTree::createAndBulkLoadNewRTree(
        switch (m)
        {
        case BLM_STR:
-               bl.bulkLoadUsingSTR(static_cast<RTree*>(tree), stream, bindex, bleaf, 10000, 100);
+               bl.bulkLoadUsingSTR(static_cast<RTree*>(tree), stream, bindex, bleaf, std::numeric_limits<uint32_t>::max(), 1);
                break;
        default:
                throw Tools::IllegalArgumentException("createAndBulkLoadNewRTree: Unknown bulk load method.");
```

**Comment by jrper** [comment]
Has this been fixed/changed upstream? I understand from @tmbgreaves that the version of spatialindex used in fluidity is getting fairly old.

**Comment by jrmaddison** [comment]
This remains an issue when using libspatialindex 1.8.5.

**Comment by jrmaddison** [comment]
Also this isn't a bug exactly - libspatialindex is designed to cache data on disk. The issue is that the cache size is not exposed in the bulk loader interface used by Fluidity.

**Comment by jrper** [comment]
Is the alternative to fix fluidity to use the other overloaded method which takes a property set for input? Or does that do something we don't want?

**Comment by jrmaddison** [comment]
I think you're right, that seems to be a way to do this.
