### ISSUE TITLE
Strain_rate_second_invariant not working for Discontinuous Velocity field

### ISSUE THREAD

**Issue by gdeskos** [FluidityProject/fluidity#123]
Deal all,

I tried to compute the strain rate second invariant using P1DG-P2  and I received an error message saying that this diagnostic field is not available for discontinuous fields. I tried to use a vector galerkin projection to create a continuous velocity field but the strain_rate_second_invariant algorithm does not give me the option to use the new continuous field. I could perhaps use remap_fields within the strain rate routine just for my own branch but I felt that this is something that might has happened to other people and needs to be fixed also in the master branch.

Thanks,
Yorgos

**Comment by stephankramer** [comment]
Hm, actually looking at the code that compute the strain_rate - strain_rate() in femtools/Field_derivatives.F90 it can actually compute it just fine directly of a discontinuous velocity field. So maybe we should just remove that call to check_source_mesh_derivative.

Two further suggestions:
* the way you can probably set this up currently (suggested by @cianwilson, haven't tried) is by adding a separate diagnostic tensor field that uses the strain_rate algorithm, and then use the tensor_second_invariant to compute the second invariant of that
* for consistency it would probably make sense that if strain_rate allows you to specify the vector field from which to compute the strain rate, then strain_rate_second_invariant should probably as well. Feel free to change that on a branch and put it up for a PR.

**Comment by jrper** [comment]
One thing to be careful of with either approach is which definition of the second invariant is actually being used. From previous offline discussion with @gdeskos, he is actually using this to calculate a Q criterion to locate vortices, and I can't off the top of my head remember whether the definition in the diagnostics agrees regarding the location of squares/square roots and in factors of two (not that all authors do either). I think I've got a branch which calculates (potentially normalised) Q criteria in a way consistent with the ParaView definition sat in a branch. I'll try and dig it out and link to it now while I remember.

**Comment by jrper** [comment]
My old attempt at diagnostic code for a Q criterion is now up at d79dd8273f9a09ecbe2efff367afddc5db2acf10.

**Comment by stephankramer** [comment]
Again, it doesn't like anyone is working on this - so closing for now
