### ISSUE TITLE
Near wall damping functions for the classic smagorinsky SFS model non-existent for continuous Galerkin 

### ISSUE THREAD

**Issue by gdeskos** [FluidityProject/fluidity#137]
Dear all,

I have noticed that the classic damping functions like the van Driest one, which are usually used along with the second order SFS Smagorinsky model is not available for continuous Galerkin discretization of the velocity field while it is for the discontinuous one. I believe that the LES options should not be different for the two formulations and thus the options in diamond should be identical. Also, I found the van Driest function in Momentum_DG.F90 and not LES.F90, which is very confusing . I would be happy to help changing this.

Kind regards,
Yorgos

**Comment by stephankramer** [comment]
I don't believe anyone is working on this at the moment. So closing for now
