### ISSUE TITLE
fluidity package does not depend on petsc

### ISSUE THREAD

**Issue by stephankramer** [FluidityProject/fluidity#144]
The fluidity Ubuntu/Debian binary package does not depend on the petsc package it has been linked against. This means that if people follow the instructions in the manual on a clean system, they will get an error when trying to run fluidity.

**Comment by tmbgreaves** [comment]
Whoops! Good spot there - I'll fix.

On similar lines, do people still regard it as reasonable that we need users to set PETSC_DIR and LD_LIBRARY_PATH at runtime? We had opted for that as it makes it a bit less of a forced choice of PETSc version system-wide, but I am curious what real world opinion says about it having tried it for a while.

**Comment by tmbgreaves** [comment]
Packages updated and new versions for trusty and xenial pushed to ppa.
