### ISSUE TITLE
Performance/Features compared to OpenFoam

### ISSUE THREAD

**Issue by Immortalin** [FluidityProject/fluidity#167]
How does this compare to OpenFoam? Does Fluidity support supersonic flow simulation?

**Comment by stephankramer** [comment]
With *this* I presume you mean Fluidity? That's a bit of a general question, but the main differences are that Fluidity is based on finite element discretisations. Another thing is that Fluidity offers anisotropic mesh refinement (as opposed to more traditional hierarchical AMR). The focus has traditionally been more on incompressible flow, although there is some compressible functionality as well, but afaik the applications of that are more in the atmosphere realm. So to answer your second question, no I don't think Fluidity is really suitable for supersonic flows or shocks - I've done some experiments in the past, but that's never been pursued further afaik. It fundamentally does not solve the equations in conservation form.

**Comment by Immortalin** [comment]
Thanks
