### ISSUE TITLE
Statplot graphical artifact

### ISSUE THREAD

**Issue by Patol75** [FluidityProject/fluidity#174]
Dear all,

Most of you may be aware of a small graphical artifact that affects statplot. Currently, the displayed plot links the last point to the first one as displayed on the attached picture.
![oldstatplot](https://user-images.githubusercontent.com/23244688/35371134-75512fe2-01e6-11e8-8f36-030e89b9a2df.png)
A web search tended to point out that this behaviour is Gtk-related. I therefore tried to modify the python scripts (tools/statplot.py, python/fluidity/diagnostics/gui.py & python/fluidity/diagnostics/plotting.py) so that they could run with the latest version of Gtk.
I created a branch called Staplot_Gtk3 which contains the three modified scripts. Roughly, Gtk 3.0 is now used with GTK3Cairo backend in Matplotlib. I also used argparse instead of getopt as it is marked as deprecated by the new Python standard. The result is included below.
![newstatplot](https://user-images.githubusercontent.com/23244688/35371141-7c9ed146-01e6-11e8-80bc-c444c4793c0f.png)
There is however a problem: when I finished all the modifications, I had the issue that the statplot window would close without reopening whenever a field modification (i.e. x- or y-axis field) would be performed. I could not figure out how to fix it, but I found out that adding those two lines:
window.show_all(),
Gtk.main(), at the end of the _RefreshPlot def (StatplotWindow class, statplot.py) would help. It is however a mystery for me, as the first line in particular should have the whole program to crash because the variable window is not declared at this stage. Indeed, the program produces an error, but the statplot window stays opened and one can display each and every combination of variables he/she wants.

Would anyone have thoughts on this ? Thank you indeed for any.

Thomas

**Comment by stephankramer** [comment]
Unfortunately I don't have much experience tinkering with gtk. Hopefully @cianwilson does? One request though: could you separate the changes you've made to these files into:
* changes needed to switch to gtk3
* changing from getopt to argparse
* arbitrary cleaning up and python style improvements.

at the very least into separate commits.

At the moment it's very hard to actually work out what you've changed. In general arbitrary cleaning of code is something that should be avoided in multi-developer projects such as this for a number of reasons:
* it makes it hard for other people to see what you've done
* when your commits are merged amongst many others it makes it hard to see what code has actually really changed over a certain time-window and who's done what (git annotate)
* chances of introducing unintended bugs and the work that inflicts on others typically doesn't outweigh the positives of having a nice looking, clean code

That's not to say I don't approve of nice and clean code :-) If you want clean up some of the code feel free to propose it, but please keep it separate from actual functional changes.

**Comment by Patol75** [comment]
Thank you for the comment Stephan.

So, what I can say is that there are no big changes, it is mostly re-naming to account for Gtk 3. For example, few functions were deprecated (as the ones to declare boxes), so I replaced them. Most of those changes are in statplot.py. A change in plotting.py is the use of a different matplotlib backend, but again that is just changing names, nothing more.
For argparse, I added comments in the statplot.py script. Basically, I removed everything linked to getopt and wrote the equivalent with argparse, ending up with a much more compact result, as the library does it all for you.
Regardind Python styling, I modified the way the files are indented, replaced all occurences of "if not X is Y" with "if X is not Y", and only rewrote the part associated to the combos in the __init__ def of the StaplotWindow class (and indeed all the import blocks).

I totally agree that it is hard to see the changes on GitHub, but I think it is related to the fact that the indentation was modified and so it looks like everything has been changed. I will keep it in mind for the next time I do modifications on such files (it would be probably better to first commit files for which only indentation is changed, or keep the indentation as it is, but I find it difficult to read...).

Thomas

**Comment by Patol75** [comment]
Dear all,

Following Stephan's comment, I have created another branch (Staplot_Gtk3_TheTwoTowers) that has three commits.
The first one deals with Getopt/Argparse.
The second with Gtk/MatplotlibBackend.
The third with the temporary workaround that I found.
It looks like my text editor (Atom) automatically corrects for blank lines that contain whitespaces, so apologies for this as it is being displayed by Git.
Nothing else has been modified. As a result, the two branches I created are different. Nevertheless, the problem depicted earlier still exists.
Hopefully this time it will be easier to have a look at.

Thomas

**Comment by Patol75** [comment]
Dear all,
I tried to figure out what was wrong, but could not find it. So I just rewrote the whole plotting interface.
The result is embedded below. It only calls classes/definitions from fluidity.diagnostics.fluiditytools. You can easily try it by executing the whole code as a .py script. If you think it is a useful improvement for fluidity, I am happy to hear from you on how to modify it so that it fits inside the framework.

Thomas

`#!/usr/bin/python
#
# James Maddison
# Thomas Duvernay

import argparse
import sys
import time

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

import matplotlib
from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo
from matplotlib.backends.backend_gtk3 import NavigationToolbar2GTK3
import matplotlib.pyplot as plt
import matplotlib.ticker as tck

import fluidity.diagnostics.fluiditytools as fluidity_tools

parser = argparse.ArgumentParser()
parser.add_argument('statfile', nargs=1)
args = parser.parse_args(sys.argv[1:])


class StatplotWindow(Gtk.Window):
    def __init__(self, filenames):
        Gtk.Window.__init__(self, title=filenames[-1])

        stats = []
        for i, filename in enumerate(filenames):
            failcount = 0
            while failcount < 5:
                try:
                    stats.append(fluidity_tools.Stat(filename))
                    break
                except TypeError, ValueError:
                    time.sleep(0.2)
                    failcount += 1
            if failcount == 5:
                raise Exception("Could not open %s" % filename)
        if len(stats) == 1:
            self._stat = stats[0]
        else:
            self._stat = fluidity_tools.JoinStat(*stats)
        del stats
        paths = sorted(self._stat.Paths())

        self._vBox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.add(self._vBox)
        self._hBox = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL)
        self._vBox.pack_end(self._hBox, False, False, 0)
        self._xCombo = Gtk.ComboBoxText()
        self._yCombo = Gtk.ComboBoxText()
        for path in paths:
            self._xCombo.append_text(path)
            self._yCombo.append_text(path)
        if "ElapsedTime" in paths:
            ind = paths.index("ElapsedTime")
            iterx = self._xCombo.get_model().get_iter("%d" % ind)
            if ind == 0:
                itery = self._yCombo.get_model().get_iter(1)
            else:
                itery = self._yCombo.get_model().get_iter_first()
        else:
            iterx = self._xCombo.get_model().get_iter_first()
            itery = self._yCombo.get_model().get_iter(1)
        self._xCombo.set_active_iter(iterx)
        self._yCombo.set_active_iter(itery)
        self._hBox.pack_start(self._xCombo, True, True, 0)
        self._hBox.pack_end(self._yCombo, True, True, 0)

        self._fig, self._ax = plt.subplots(nrows=1, ncols=1, num=0)
        self._fig.tight_layout()
        self._canvas = FigureCanvasGTK3Cairo(self._fig)
        self._toolbar = NavigationToolbar2GTK3(self._canvas, None)
        self._PlotData()
        self._fBox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self._fBox.pack_start(self._canvas, True, True, 0)
        self._fBox.pack_end(self._toolbar, False, False, 0)
        self._vBox.pack_start(self._fBox, True, True, 0)

        self._xCombo.connect("changed", self._ComboChanged)
        self._yCombo.connect("changed", self._ComboChanged)

        return

    def _ComboChanged(self, widget):
        self._PlotData()

        return

    def _PlotData(self):
        self._xField = self._xCombo.get_active_text()
        self._yField = self._yCombo.get_active_text()
        self._xData = self._stat[self._xField]
        self._yData = self._stat[self._yField]
        self._ax.cla()
        self._ax.plot(self._xData, self._yData, linewidth=2)
        if self._xField == 'ElapsedTime':
            self._ax.set_xlim([-0.02 * max(self._xData),
                               1.02 * max(self._xData)])
        self._ax.ticklabel_format(style='sci', axis='both', scilimits=(0, 0))
        self._ax.set_xlabel(self._xField, fontweight='bold', fontsize=20)
        self._ax.set_ylabel(self._yField, fontweight='bold', fontsize=20)
        self._ax.xaxis.set_minor_locator(tck.AutoMinorLocator(5))
        self._ax.yaxis.set_minor_locator(tck.AutoMinorLocator(5))
        self._ax.tick_params(which='major', length=7, labelsize=15, width=2)
        self._ax.tick_params(which='minor', length=4, width=2, color='r')
        self._fig.canvas.draw()

        return


window = StatplotWindow(args.statfile)
window.connect("delete-event", Gtk.main_quit)
window.set_default_size(1600, 900)
window.set_position(Gtk.WindowPosition.CENTER)
window.show_all()
Gtk.main()
`

**Comment by Patol75** [comment]
I am closing this following #190 being merged.
