### ISSUE TITLE
Fluidity does not build on Ubuntu Bionic (18.04 LTS)

### ISSUE THREAD

**Issue by tmbgreaves** [FluidityProject/fluidity#177]
This issue documents the ongoing build debugging for Ubuntu Bionic (18.04 LTS) on a pre-release buildbot builder at:

http://buildbot.ese.ic.ac.uk:8080/builders/bionic-standard

**Comment by tmbgreaves** [comment]
PETSc 3.8 is not currently supported on master, build building with the petsc38-changes branch gets through configure. Reference issue #173

**Comment by tmbgreaves** [comment]
With the petsc38-changes branch, the build fails with an ICE:

http://buildbot.ese.ic.ac.uk:8080/builders/bionic-standard/builds/4/steps/shell_2/logs/stdio

gfortran version is: GNU Fortran (Ubuntu 7.3.0-3ubuntu1) 7.3.0

        FC Polynomials.F90
f951: Warning: Nonexistent include directory 'include/' [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory 'include/' [-Wmissing-include-dirs]
f951: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
Makefile:123: recipe for target 'Polynomials.o' failed
make[1]: *** [Polynomials.o] Error 1
make: *** [lib/libfluidity.a] Error 2
Makefile:228: recipe for target 'lib/libfluidity.a' failed

**Comment by jrper** [comment]
Do we have any successful builds with gcc 7.3 on any other systems? The latest version I'm building with is 7.2 on Apple.

**Comment by tmbgreaves** [comment]
I don't think we do - all the others on buildbot are 6.x or earlier.

**Comment by jrper** [comment]
I've found a Mac OS X package for 7.3.0, so I'm having a go at building master with that, in case we're running into one of the regression errors fortran seems to have picked up.

**Comment by jrper** [comment]
The Macports package of 7.3.0 builds and runs master successfully, so this is Ubuntu 18.04 related rather than purely a compiler problem.

**Comment by tmbgreaves** [comment]
Thanks James.

**Comment by tmbgreaves** [comment]
Appears to have been fixed upstream, building as of:
http://buildbot.ese.ic.ac.uk:8080/builders/bionic-standard/builds/5/steps/shell_2/logs/stdio
