### ISSUE TITLE
building issue with libspud

### ISSUE THREAD

**Issue by guoxiaohu** [FluidityProject/fluidity#186]
I have tried to build fluidity together with intel/18.0.128

I have got the following error 

MKDIR lib
echo '    MAKE libspud'; gmake -s -C libspud &&  gmake -s -C libspud install-libspud && cd libspud/python && python setup.py build && cd ../.. && cp libspud/python/build/lib*/libspud.so python/
    MAKE libspud
libtool: compile:  ifort -Iinclude -DMPICH_IGNORE_CXX_SEEK -DNDEBUG=1 -O3 -i8 -I/lustre/scafellpike/local/apps/intel/intel_cs/2018.0.128/mkl/include/intel64/ilp64 -I/lustre/scafellpike/local/apps/intel/intel_cs/2018.0.128/mkl/include -I/usr/include -extend_source -c src/fspud.f90  -fPIC -o .libs/fspud.o
src/fspud.f90(295): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat =  spud_load_options(string_array(filename), len_trim(filename))
-------------------------------------------------------^
src/fspud.f90(310): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_write_options(string_array(filename), len_trim(filename))
-------------------------------------------------------^
src/fspud.f90(333): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_get_child_name(string_array(key), len_trim(key), index, lchild_name, size(lchild_name))
---------------------------------------------------^
src/fspud.f90(333): warning #6075: The data type of the actual argument does not match the definition.   [INDEX]
    lstat = spud_get_child_name(string_array(key), len_trim(key), index, lchild_name, size(lchild_name))
------------------------------------------------------------------^
src/fspud.f90(333): warning #6075: The data type of the actual argument does not match the definition.   [SIZE]
    lstat = spud_get_child_name(string_array(key), len_trim(key), index, lchild_name, size(lchild_name))
--------------------------------------------------------------------------------------^
src/fspud.f90(350): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_get_number_of_children(string_array(key), len_trim(key), child_count)
-----------------------------------------------------------^
src/fspud.f90(350): error #6633: The type of the actual argument differs from the type of the dummy argument.   [CHILD_COUNT]
    lstat = spud_get_number_of_children(string_array(key), len_trim(key), child_count)
--------------------------------------------------------------------------^
src/fspud.f90(363): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    option_count = spud_option_count(string_array(key), len_trim(key))
--------------------------------------------------------^
src/fspud.f90(372): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    have_option = (spud_have_option(string_array(key), len_trim(key)) /= 0)
-------------------------------------------------------^
src/fspud.f90(388): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_get_option_type(string_array(key), len_trim(key), option_type)
----------------------------------------------------^
src/fspud.f90(388): error #6633: The type of the actual argument differs from the type of the dummy argument.   [OPTION_TYPE]
    lstat = spud_get_option_type(string_array(key), len_trim(key), option_type)
-------------------------------------------------------------------^
src/fspud.f90(408): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_get_option_rank(string_array(key), len_trim(key), option_rank)
----------------------------------------------------^
src/fspud.f90(408): error #6633: The type of the actual argument differs from the type of the dummy argument.   [OPTION_RANK]
    lstat = spud_get_option_rank(string_array(key), len_trim(key), option_rank)
-------------------------------------------------------------------^
src/fspud.f90(428): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_get_option_shape(string_array(key), len_trim(key), option_shape(1:2))  ! Slicing required by GCC 4.2
-----------------------------------------------------^
src/fspud.f90(428): error #6633: The type of the actual argument differs from the type of the dummy argument.   [OPTION_SHAPE]
    lstat = spud_get_option_shape(string_array(key), len_trim(key), option_shape(1:2))  ! Slicing required by GCC 4.2
--------------------------------------------------------------------^
src/fspud.f90(463): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(key, len_trim(key), c_loc(lval))
-----------------------------------^
src/fspud.f90(494): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(526): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(559): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(592): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(625): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(656): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(687): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(718): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(756): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
      lstat = spud_get_option(string_array(key), len_trim(key), c_loc(lval))
-------------------------------------------------^
src/fspud.f90(776): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_add_option(string_array(key), len_trim(key))
-----------------------------------------------^
src/fspud.f90(795): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val), SPUD_REAL, 0, (/-1, -1/))
-----------------------------------------------^
src/fspud.f90(795): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val), SPUD_REAL, 0, (/-1, -1/))
------------------------------------------------------------------------------------------^
src/fspud.f90(818): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_REAL, 1, (/size(val), -1/))
-----------------------------------------------^
src/fspud.f90(818): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_REAL, 1, (/size(val), -1/))
-------------------------------------------------------------------------------------------^
src/fspud.f90(840): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val_handle), SPUD_REAL, 2, shape(val_handle))
-----------------------------------------------^
src/fspud.f90(840): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val_handle), SPUD_REAL, 2, shape(val_handle))
-----------------------------------------------------------------------------------------------^
src/fspud.f90(863): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_REAL, 0, (/-1, -1/))
-----------------------------------------------^
src/fspud.f90(863): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_REAL, 0, (/-1, -1/))
-------------------------------------------------------------------------------------------^
src/fspud.f90(886): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_REAL, 1, (/size(val), -1/))
-----------------------------------------------^
src/fspud.f90(886): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_REAL, 1, (/size(val), -1/))
-------------------------------------------------------------------------------------------^
src/fspud.f90(910): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val_handle), SPUD_REAL, 2, shape(val_handle))
-----------------------------------------------^
src/fspud.f90(910): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val_handle), SPUD_REAL, 2, shape(val_handle))
-----------------------------------------------------------------------------------------------^
src/fspud.f90(929): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val), SPUD_INTEGER, 0, (/-1, -1/))
-----------------------------------------------^
src/fspud.f90(929): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val), SPUD_INTEGER, 0, (/-1, -1/))
---------------------------------------------------------------------------------------------^
src/fspud.f90(951): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_INTEGER, 1, (/size(val), -1/))
-----------------------------------------------^
src/fspud.f90(951): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_INTEGER, 1, (/size(val), -1/))
----------------------------------------------------------------------------------------------^
src/fspud.f90(973): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val_handle), SPUD_INTEGER, 2, shape(val_handle))
-----------------------------------------------^
src/fspud.f90(973): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(val_handle), SPUD_INTEGER, 2, shape(val_handle))
--------------------------------------------------------------------------------------------------^
src/fspud.f90(995): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_CHARACTER, 1, (/len_trim(val), -1/))
-----------------------------------------------^
src/fspud.f90(995): error #6633: The type of the actual argument differs from the type of the dummy argument.
    lstat = spud_set_option(string_array(key), len_trim(key), c_loc(lval), SPUD_CHARACTER, 1, (/len_trim(val), -1/))
------------------------------------------------------------------------------------------------^
src/fspud.f90(1017): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option_attribute(string_array(key), len_trim(key), lval, len_trim(val))
---------------------------------------------------------^
src/fspud.f90(1017): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_set_option_attribute(string_array(key), len_trim(key), lval, len_trim(val))
------------------------------------------------------------------------------^
src/fspud.f90(1036): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_move_option(string_array(key1), len_trim(key1), string_array(key2), len_trim(key2))
-------------------------------------------------^
src/fspud.f90(1036): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_move_option(string_array(key1), len_trim(key1), string_array(key2), len_trim(key2))
-------------------------------------------------------------------------------------^
src/fspud.f90(1055): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_copy_option(string_array(key1), len_trim(key1), string_array(key2), len_trim(key2))
-------------------------------------------------^
src/fspud.f90(1055): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_copy_option(string_array(key1), len_trim(key1), string_array(key2), len_trim(key2))
-------------------------------------------------------------------------------------^
src/fspud.f90(1073): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
    lstat = spud_delete_option(string_array(key), len_trim(key))
--------------------------------------------------^
compilation aborted for src/fspud.f90 (code 1)
gmake[1]: *** [fspud.lo] Error 1
make: *** [/gpfs/fairthorpe/local/package_build/build/xxg06-build/fluidity/lib/libspud.a] Error 2

**Comment by stephankramer** [comment]
I've opened an issue here: https://github.com/FluidityProject/spud/issues/4

**Comment by guoxiaohu** [comment]
Thanks for help out, it is the issue of -i8, libspud has now been built successfully.
