### ISSUE TITLE
BuildBot testing logs

### ISSUE THREAD

**Issue by Cmath2** [FluidityProject/fluidity#195]
I'm currently working on the branch 'chris_particles', and am coming across some discrepancies between locally hosted versions of the branch and the one built and tested on BuildBot. 

Starting on a clean directory, I can pull the branch to my local system and it will pass all short tests. The version built on BuildBot, however, appears to run into segmentation faults for two of the tests. http://buildbot.ese.ic.ac.uk:8080/builders/chris_particles/builds/7/steps/shell_8/logs/stdio 

Is it possible to receive a more in depth version of the testing logs (either through TAR files of the logs or a backtrace of the errors)?

If it helps, I'm on Ubuntu 16.04, and am compiling with GCC 5.4 and mpi 1.10.2

Thanks
Chris

**Comment by tmbgreaves** [comment]
Hi Chris,

Are you able to run a docker container locally? If so, you should be able to exactly replicate the buildbot environment with an interactive shell by running:

docker run -it --workdir=/home/fluidity/fluidity -u fluidity -t fluidity/buildbot:chris_particles-latest-pretest bash -il

... and then either run the tests individually, or 'make test'.

If you don't have docker set up yet, there are instructions at:

https://docs.docker.com/install/linux/docker-ce/ubuntu/

Hope that helps to debug the tests!

Tim
