### ISSUE TITLE
Error when using multiple material fields with regions of precribed velocity

### ISSUE THREAD

**Issue by benmaunder** [FluidityProject/fluidity#197]
Apologies that this is vague. I have been trying to develop a model with multiple material fields but that also contains a region where the velocity field is prescribed. I have found that, no matter what I do, I get the following error immediately upon running fluidity:

Option key error. Key is: /vector_field::Velocity/aliased/material_phase_name

I am using the current master.

I have created a simplified test model which reproduces the error, which I have attached. It comes with a read me file with a bit more information.

[mat_field_test.zip](https://github.com/FluidityProject/fluidity/files/1989116/mat_field_test.zip)

Best wishes, 

Ben Maunder

**Comment by Patol75** [comment]
Dear Ben,

I am able to reproduce the issue on my system.
I do not have much input about why it fails, however diamond documentation says the following for the region_ids key:

>  Optional region ids to associate different values to different regions of the mesh. Leave unselected if you`re not using multiple regions or region_ids. Currently only works with triangle files created by gmsh2triangle.

In the fluidity manual, there is:

> Please note that use of the Triangle mesh format is now DEPRECATED!

Another thing is that we are dealing here with a region_ids key. Do you know if there is any difference with a surface_ids key ?

Thomas

**Comment by jrper** [comment]
This appears to be an issue in the interaction between the multimaterial code and the sub_state code which allows velocity fields to be split into prescribed and prognostic regions. It seems that while the substate material phases inherit the names of their parent, they don't inherit the `options_path` variable which the multilateral code needs in order to find additional data.

It's possible that the fix is as simple as adding a function to copy the `options_path`s somewhere inside `preprocessor/Popultate_Sub_State.F90`
but since this code path is sufficiently untested that you're seeing that error, I'm not certain that this won't break something else.

**Comment by stephankramer** [comment]
Yes, @jrper is exactly right. I've just pushed a branch with that fix in: [substate-optionpath](https://github.com/FluidityProject/fluidity/tree/substate-optionpath)

Could you checkout that branch and see if it works for you? One word of warning though: I think this indeed means that "substate" (having a partially prescribed velocity) has not been used in combination with multimaterial before, so there might be other issues you encounter. Let us know if you do.

**Comment by benmaunder** [comment]
Hi All, 

Thanks for looking at this. That has indeed removed the error and the test model does now run. However, the test model now demonstrates some peculiar behaviour during the initial timestep:
- All material fields inside the prescribed region gets advected during the first timestep (seemingly also twice as fast as it should) whereas material outside doesn't.
- During the first timestep, the internal boundary between the prescribed region and the rest of the model domain behaves like an external boundary (i.e. any material advected out of the prescribed region is lost etc.).

I've updated the minimal reproducer so that the x and y positions of the material block and the x and y components of the velocity field applied to the prescribed region and boundaries can be set in the constants file.

[mat_field_test.zip](https://github.com/FluidityProject/fluidity/files/2005677/mat_field_test.zip)
