### ISSUE TITLE
Ubuntu packages for petsc and zoltan

### ISSUE THREAD

**Issue by stephankramer** [FluidityProject/fluidity#202]
I'd like to discuss the Ubuntu package we build as dependencies for fluidity, in particular petsc and zoltan. I'd like to propose going back to a more standard petsc package and build zoltan linked against the standard Ubuntu scotch and parmetis packages. The motivations are:
 1) to make it possible to build your own petsc or use a standard Ubuntu/Debian petsc package without having to build your own zoltan package. The current zoltan package installs its libraries in a petsc /usr/lib/petscdir.../ hard-coded to match the specific petsc package that we build for fluidity
2) to simplify and reduce maintenance in the future. The installation procedure of petsc tends to get changed quite often and also the Debian and Ubuntu maintainers have changed how they deal with petsc's idiosyncracies over time (for instance for the petsc-3.8 packages there will now be specific real and complex versions which changes the naming scheme of the packages). With every change we need to ensure that our specific adjustments to the petsc packages are ported across. As I will argue below most (if not all) these adjustments are no longer required.

My proposal is:
1) to use the standard libparmetis4.0 Ubuntu Debian package everywhere
2) to build zoltan linked with parmetis and scotch from standard Ubuntu/Debian packages
3) go back to the standard petsc package and only provide our own petsc package if we require a newer version, which we can do by simply backporting (download the source and rebuild) from Debian Unstable

It's only a proposal, and I'm happy to hear objections. In particular, I'd like to have feedback from @tmbgreaves (as he's the one who's done most of the hard work in this area), @jrper, @drhodrid and @cianwilson 

We currently build our own version of the petsc package for two reasons 1) to add extra petsc dependencies and 2) we sometimes want to have a newer version than the offical Ubuntu package.
I think most of the extra petsc dependencies are now in the official package as well: mumps, scotch, hypre, scalapack, suitesparse. Dependencies that are not:
*) ctetgen, triangle - these are mesh generation, so I don't know why we need them as libraries. For the triangle executable, there is the triangle-bin package
*) excodus is included as a dependency but doesn't seem to get installed
*) ml - this is a algebraic multigrid preconditioner that we in the past have tried to use but never got much out of afaik
*) chaco - this is a partioner (dead project) - if we need it at all we only need to build as a dependency of zoltan
*) sowing, not sure what we need that for
*) parmetis/metis: see discussion below
So in short, I don't think any of these are still relevant. If people do find some of them relevant, I would like to hear from them. Finally there are also dependencies that are in the official package (superlu for instance), but we don't currently provide.

So the big bugbear is parmetis/metis and in particular issues surrounding conflicting versions. There are 3 different ways it can be accessed:
1) fluidity directly uses metis in fldecomp (a dependency we've previously considered dropping, but I don't think it's necessary for what I'm proposing)
2) the normal way we access it is via zoltan, in which case it is the parmetis library that was linked against when zoltan was built
3) it can come in via petsc. This is optional. I think it can be used by mumps? In any case in my experience using scotch for mumps works just as well
The main issue previously was that fluidity fldecomp didn't link with the latest metis version, but petsc would require a newer version and we'd get conflicts. I don't think any of these reasons are still true and we should be able to just use the (non-free) libparmetis4.0 package everywhere.

FWIW: I've been using this approach on a continuously upgrading Debian testing/unstable system for the last 2 years. The changes to our current zoltan package (which I rebuild locally from time to time) are minimal, and I'm using standard Debian petsc 3.8 with that with no problem. Everything linked with libparmetis4.0.

**Comment by tmbgreaves** [comment]
I like this idea a lot, as it would get rid of one of our most problematic local ubuntu packages. I'm still in a Jenkins-focused mindset at the moment but once that's somewhere near done I'll get thinking about packaging.

**Comment by tmbgreaves** [comment]
(The current Ubuntu petsc packages we build have a lot of really nasty hacks to get things working without spending too much time tinkering with the fine details, so I think there would be few people happier than me to consign them to silicon heaven)

**Comment by jrper** [comment]
No objections to moving to system libraries as a default. If we're considering doing that for PETSc, are libjudy and spatialndex also on the table?

**Comment by tmbgreaves** [comment]
My initial thought is that those are potentially more complicated as we'd end up losing complexity in the fluidity configure/build but gaining on platforms where libjudy and spatialindex aren't pre-packaged, including a lot of HPC systems and (I guess) RHEL. Possibly an option would be to have them as opt-in as opposed to automatic parts of the fluidity build?

**Comment by tmbgreaves** [comment]
Continuing to be mired in Jenkins but this is high on my list of things to look at once I'm slightly more in control of CI.

**Comment by stephankramer** [comment]
FWIW, see attached for the only changes I had to make to our zoltan package. With this package and using a standard petsc 3.8 package (and parmetis4 and (pt)scotch packages), fluidity builds on Debian Buster. The only thing is, that I currently need to give it `FCFLAGS=-I/usr/include` for it to find zoltan.mod (something we should probably add as directory to look for in configure).

[patch.txt](https://github.com/FluidityProject/fluidity/files/2090362/patch.txt)

**Comment by jrper** [comment]
Speaking as the token mac user, I'd hope we can do something more intelligent than just dumping `/usr/include` straight into FCFLAGS, but I'm not upset by any of the rest of that.

**Comment by tmbgreaves** [comment]
Starting to look at this now - do either of you have a feel for whether it's feasible to also drop our zoltan package and use the libtrilinos-zoltan* packages instead?

**Comment by jrper** [comment]
I've got a nasty suspicion that none of the regular packaged versions include the in-house Zoltan Fortran bindings. We could presumably generate our own, and link to the C versions of functions instead, but I don't think that counts as reducing our support burden.

**Comment by guoxiaohu** [comment]
If you ask PETSc people nicely, they could add option with Zoltan fortran support.  or simply patch 

petsc/config/BuildSystem/config/packages/Zoltan.py

**Comment by nkr1729** [comment]
Actually I got this [merged](https://bitbucket.org/petsc/petsc/pull-requests/582/small-patch-to-enable-zoltans-f90/diff) into petsc quite a while back. It is part of petsc>=3.9.

**Comment by tmbgreaves** [comment]
Genius - thank you :-) In which case, the question moves on to whether we can get Fluidity supporting PETSc 3.9...

**Comment by nkr1729** [comment]
ongoing conversation at #218 #224 and #225 . I can confirm that `make && make fltools` complete without errors with `petsc3.11`. But I haven't run any simulations yet. So there could be run-time errors.

**Comment by tmbgreaves** [comment]
This has now happened as of Ubuntu Focal, though some thought may need to be put in for Ubuntu 'J' / 22.04 if it ends up on petsc < 3.16 with the PETSc Fortran bug that matters to us. Hirsute is on 3.14.6 and Debian bleeding edge is at 3.15 so I'm hopeful by the time 22.04 gets a package version freeze we'll be in the clear.
