### ISSUE TITLE
Question about transform_cvsurf_to_physical

### ISSUE THREAD

**Issue by stevendargaville** [FluidityProject/fluidity#206]
Hi all

Bit of an odd question, I have some tests that have recently started failing when building a model of darcy flow in Fluidity. I have inherited these tests so have no real idea what they're doing, but have attached a msh and flml

[test_darcy.zip](https://github.com/FluidityProject/fluidity/files/2116326/test_darcy.zip)

The issue comes in assemble_divergence_matrix_cv, when calling transform_cvsurf_to_physical. The jacobian is calculated in the 1D case, even though detJ=1.0. With debugging on,  the matmul on line 2326 fails with a runtime error, as J is size 1x1, X is 1x2 and x_shape%dn(:, ggi, :)) is 2x0.

Without debugging, this just generates NaN in J, which is then not used and the simulation completes and all the tests pass. I suppose my question is whether this is expected behaviour? Perhaps the tests I've inherited are specifying something nonsensical?

**Comment by stephankramer** [comment]
Not sure how relevant this still is, but I have two questions:

1) I'm a little puzzled actually why detJ=1.0 in the first place. It's in all the various versions of transform_to_physical but it makes no sense to me - then again this would mean all line integrals would be wrong, so I'm clearly missing something
2) why is `x_shape%dn(:, ggi, :))` is 2x0 that should be 2x1, no?

**Comment by stephankramer** [comment]
Discussing this with @jrper has unconfused me a little: what I missed was `transform_cvsurf_to_physical` is about *surface* integrals. Thus in 1D, this is 0D surface and detJ should indeed be 1. I'm not entirely familiar with the CV element shapes that is being passed in here (`x_shape`), but they seem to also be referring to the surface and thus indeed `x_shape%dn` should be 2xngix0.

It seems that indeed the dimensions of J are wrong (also in higher dimensions) - its second dimension should be the surface dimension (i.e. dim-1). I can't actually get my compiler to complain about it, but I have attempted a fix (see above).

@stevendargaville : does this fix the issue for you? Please feel free to add more relevant tests to fluidity if that's useful for you.

**Comment by stevendargaville** [comment]
Hi @stephankramer, yes this does fix my issue. Thanks for the clarity and resolving this one :)
