### ISSUE TITLE
statplot on Ubuntu 18.04

### ISSUE THREAD

**Issue by jhill1** [FluidityProject/fluidity#209]
Hi,
Fresh install of Linux Mint 19 (Ubuntu 18.04) with the fluidity-dev package installed. statplot no longer opens as the GTK2.0 backend for matplotlib is no longer compiled into the python-matplotlib package (as far as I can tell!). I have the python-gtk2 PyGTK packages etc installed and installing matplotlib from source works fine and then I can open statplot.

It might be worth transitioning Diamond and statplot to gtk3

**Comment by jhill1** [comment]
Forgot to mention: statplot works fine apart from this depreceation warning:

**Comment by stephankramer** [comment]
For statplot on gtk3 see #190 (which I think is waiting on #180)

For diamond on gtk3 see https://github.com/FluidityProject/spud/pull/7

**Comment by jrper** [comment]
And #180 is waiting on me being trying to sort out python3 testing, which has rather fallen by the wayside, after the jenkins.ese migration left be without the permissions to experiment. @tmbgreaves is there any chance of getting them back, it only for the fluidity python3 instance?

**Comment by tmbgreaves** [comment]
Sorry @jrper - now fixed, I think. On a rubbish connection for the next couple of weeks hence not entirely sure I got the fix right. Let me know if you still don't have admin rights on Jenkins.

**Comment by stephankramer** [comment]
Fixed in #190 and FluidityProject/spud#7
