### ISSUE TITLE
vtk6 "-lvtkFiltersVerdict" dependency

### ISSUE THREAD

**Issue by nkr0** [FluidityProject/fluidity#216]
Hi,

I'm not sure when this change was introduced, (possibly vtk6.0+), in vtk6.3, vtkMeshQuality is part of vtkFiltersVerdict. I got an undefined reference error and was fixed when "-lvtkFiltersVerdict" flag was passed for LIBS.

https://github.com/FluidityProject/fluidity/blob/master/configure#L15035
https://github.com/FluidityProject/fluidity/blob/master/femtools/Mesh_Quality_C.cpp#L34

**Comment by tmbgreaves** [comment]
Ths is now wrapped into the cmake VTK autodetect, so I think can safely be closed.
