### ISSUE TITLE
MPI linking error while building tools

### ISSUE THREAD

**Issue by angus-g** [FluidityProject/fluidity#226]
I'm not really sure what the root of this one is, but during `make fltools`, three tools call for the use of `FLLINKER` (mpif90 in my case). This causes an undefined reference error linking in libfluidity, e.g.
```
../lib/libfluidity.a(C++_Debug.o): In function `MPI::Intracomm::Clone() const':
C++_Debug.cpp:(.text._ZNK3MPI9Intracomm5CloneEv[_ZNK3MPI9Intracomm5CloneEv]+0x2b): undefined reference to `MPI::Comm::Comm()'
```
just to pick an example. For reference, I get this with both OpenMPI 3.1.3 and 4.0.1.

Using the regular `LINKER` (mpicxx) links in the MPI C++ stuff and allows this compile to succeed. I don't have a working configuration without this change so I'm hesitant to suggest anything further.

**Comment by jrper** [comment]
I'm fairly confident that as long as we're only officially supporting GCC and friends, then switching out the linker won't break anything, since libgfortran seems to always end up being linked in. This might still cause failures for anyone on intel, or more esoteric compilers on HPC. I'm a lot less certain about how you're needing C++ MPI wrappers at all, given that #196 pretty much removed every reference, given that the MPI v3 standard deprecates them anyway.

**Comment by jrper** [comment]
Actually, @angus-g, are you running on an OS with system packages for openmpi 2.0+, or this is something self-compiled?

**Comment by angus-g** [comment]
@jrper So 4.0.1 (+ GCC) is on my local system, and it looks as though it's compiled with `--enable-mpi-cxx`. I was using 3.1.3 (+ Intel) on our HPC, so not a system package but not self-compiled either. Given that the mpicxx include files are available here too, I'm guessing this also has `mpi-cxx` enabled...

I guess this may be partially on my end, since my OpenMPI 2.0+ packages are still including the deprecated C++ API. Maybe it'll just end up being useful to have this documented in case others run into the same problem!

**Comment by Patol75** [comment]
Confirmed issue reported by @angus-g, solution suggested works.
Ubuntu 18.04.2 LTS
Open MPI 2.1.1
GCC 7.3.0

**Comment by stephankramer** [comment]
Is this still an issue? `make fltools` works fine on my Bionic desktop, and in the fluidity container on Jenkins. Or is this only on certain branches?

**Comment by drhodrid** [comment]
@stephankramer - this recently cropped up on our move from Raijin to Gadi as well... so, yes, still an issue...

**Comment by stephankramer** [comment]
@drhodrid and/or @angus-g : could you try out the [fix-mpi-headers](https://github.com/FluidityProject/fluidity/tree/fix-mpi-headers) branch? It appears with '#include <mpi.h>' you get both c-interface and c++-interface symbols when included from a c++ file which can be avoided with some mpi-implementation specific \#defines.

**Comment by stephankramer** [comment]
The point being that we shouldn't need any c++ mpi symbols, as we no longer use the c++ interface (which is deprecated).

**Comment by angus-g** [comment]
Thanks @stephankramer, that branch does appear to have fixed the compilation issue for me on Gadi.
