### ISSUE TITLE
Multiphase vs Multimaterial approaches

### ISSUE THREAD

**Issue by luckyluckyluc** [FluidityProject/fluidity#229]
Hello,

I am a new fluidity user for two-phase flow modelling. Ideally, I would like to use an **Eulerian-Eulerian approach** where each field has its own set of equations instead of a **VOF approach** where one set is used for both phases. I wish **both phases** to be **continuous**, however, fluidity seems to only allow for 1 continuous phase and 1 dispersed phase only (with a particle diameter to define).

I have tried to run two-phase simulations removing the _<multiphase_interaction>_ branch and _<material_phase/multiphase_properties>_ (where the particle diameter is defined) but it was unsuccessful.

So I am wondering if this kind of two-continuous-phase flow simulation is feasible without using the Multimaterial approach.

Many thanks for your help,

Best wishes,
Luc B

**Comment by ctjacobs** [comment]
Hi Luc,

The main focus of Fluidity's multiphase flow model has been dispersed multiphase flows. However, it is possible to run simulations without specifying a particle diameter and any interaction terms. An example test case is `tests/mphase_sedimentation_2d` which considers the settling out of two phases which are initially perfectly mixed (i.e. volume fraction of phase 1 = volume fraction of phase 2 = 0.5). See also `tests/mphase_three_layers` which considers 3 phases.

Chapter 4 of my thesis may be of interest if you are planning to use the model: http://hdl.handle.net/10044/1/12785

Cheers,
Christian
