### ISSUE TITLE
Building Fluidity Against Python 3.6

### ISSUE THREAD

**Issue by drhodrid** [FluidityProject/fluidity#232]
Hi devs,

Have any of you had success building Fluidity against python 3.6? I've tried this eve, but fail in libspud with the following errors:

libspud.c: In function ‘libspud_get_option_type’:
libspud.c:223:20: error: ‘PyInt_Type’ undeclared (first use in this function); did you mean ‘PySet_Type’?
         Py_INCREF(&PyInt_Type);
                    ^
/usr/include/python3.6m/object.h:785:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)
                   ^~
libspud.c:223:20: note: each undeclared identifier is reported only once for each function it appears in
         Py_INCREF(&PyInt_Type);
                    ^
/usr/include/python3.6m/object.h:785:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)
                   ^~
libspud.c:230:20: error: ‘PyString_Type’ undeclared (first use in this function); did you mean ‘PySlice_Type’?
         Py_INCREF(&PyString_Type);
                    ^
/usr/include/python3.6m/object.h:785:19: note: in definition of macro ‘Py_INCREF’
     ((PyObject *)(op))->ob_refcnt++)

Am I the only one seeing this or have others come across it? 

Rhod

**Comment by jrper** [comment]
Hi Rhodri, I think this is a case of upstream changes never getting merged. The relevant changes are stuck in https://github.com/FluidityProject/spud/pull/3, which needs some love to get merged.

**Comment by jrper** [comment]
I've put @stephankramer on the case to get that reviewed.

**Comment by drhodrid** [comment]
Thanks @jrper. Incorporating those changes got me through the build and I have a passing test suite, so things are looking promising. Over to you @stephankramer.

**Comment by drhodrid** [comment]
I just had a chat with @cianwilson about this. It seems that he has built on your changes @jrper and incorporated some additional (required) modifications relating to diamond, gtk... Everything is here: https://github.com/FluidityProject/spud/pull/7. What needs to be done to get this merged?
