### ISSUE TITLE
Explicit GMSH file format for tests?

### ISSUE THREAD

**Issue by angus-g** [FluidityProject/fluidity#233]
While Fluidity requires msh version 2 formatted files as input, some versions of GMSH will output a newer (and thus incompatible) format by default. However, GMSH supports the `-format msh2` flag and option to explicitly generate the correct version.

I'm not sure how this interacts with the versions of GMSH people currently use -- it seems like 2.x is the norm, although the upstream project is up to 4.x (and indeed that's the one I've had pulled in on my local machine).

This change really boils down to running `sed -ie 's/\bgmsh\b/gmsh -format msh2/' */Makefile` in the project root, but I wanted to check if this is sensible first before submitting a rather ugly pull request that touches every test...

**Comment by jhill1** [comment]
Would it be better/feasible to write a gmsh reader for the newer format? It would take longer (and I'm not volunteering to write it!) but it may be preferable to editing every test and make it easier to users in the long run.

**Comment by stephankramer** [comment]
Agree, it would probably be good to look into that and depending on how different the format is to support one or both. Note that we need both reading *and* writing (for checkpoints and flredecomp).

**Comment by jrper** [comment]
Essentially the biggest difference is a switch to using a more compressed, entity based system for tags, even in the ASCII format. It would be a finite, but non-trivial exercise to make a reader for both 2.X and 4.X formats.

In principle, one option would be to switch to using libgmsh to handle the actual file reading, now that the API is finished, but that would add a nasty dependency.

**Comment by jrper** [comment]
See c41e5e54fc7e169c620b10d30058d7fd2918f788 for an attempt at a reader for GMSH file formats 4 and 4.1  (i.e. the new ones). Having played with libgmsh a bit, I suspect that a hand rolled reader is the better way to go, but testing it is going to be a nightmare (I'm confident that it's trivial to break this implementation).

**Comment by angus-g** [comment]
Nice! As long as the input files don't get too esoteric I agree that this is probably the better approach. I'll have a bit of a play and see whether I can break it.

I could replicate the functionality with libgmsh pretty easily (although I didn't bother setting it up as a dependency, which seems much more painful). In this case, libgmsh is pretty simple to use (but very overkill) for this case: open a file and read off the nodes/elements. Memory management without the C++ API is a bit more painful since they don't actually detail how it works in the C API (I assume you're allowed to just free everything they allocate for you))...

**Comment by Patol75** [comment]
Just a bit of bookkeeping here, but should this issue be closed given #235?
