### ISSUE TITLE
Zero diagonal in the Poisson's solve

### ISSUE THREAD

**Issue by nkr1729** [FluidityProject/fluidity#234]
Hi,

I came across a set of conditions which lead to a zero diagonal situation in the pressure poisson's system. The equation that got the zero diagonal belongs to the node highlighted in the picture below.

![point](https://user-images.githubusercontent.com/42086312/60006480-cd841600-9670-11e9-9a2a-0fb734fb67dc.png)

However, the bottom corner node doesn't have that issue. I think the difference is that in the top corner there is only one element and all of it's nodes are fixed. Whereas in the bottom corner, there are 2 elements with 1 (shared) free node. I'm not really sure if this is a bug or if this is how it is expected, theoretically.

The mesh is the result of `hr_adaptivity` and thus this is doesn't happen always. 

I've `integrate_continuity_by_parts` **disabled**.

**Comment by nkr1729** [comment]
Perhaps, it is my `P1P1` element pair choice that shouldn't be used **without** `integrate_continuity_by_parts`.

**Comment by stephankramer** [comment]
Hm, I haven't used P1P1 for a while, but I think this is a common issue, and it's exactly as you describe it. This is with mass lumping I presume? So this may depend on boundary conditions as well. If for instance you have strong Dirichlet in both directions, then the mass-lumped diagonal is zero for all boundary nodes, in which case the rows of CMC (the discrete mass matrix) that are only connected to (other) boundary nodes are completely zero. You could try using repair_stiff_nodes which is an option (hack) to deal with this situation, although you might still see artifacts in your pressure solution (pressure from P1P1 is often a little funky anyway)...

**Comment by nkr1729** [comment]
Yes, mass is lumped. I think that explains. I see what you wrote in these lines,
https://github.com/FluidityProject/fluidity/blob/8354eddf4c1e8de492fea93ad053504620d22197/assemble/Momentum_CG.F90#L879
https://github.com/FluidityProject/fluidity/blob/8354eddf4c1e8de492fea93ad053504620d22197/preprocessor/Boundary_Conditions_From_Options.F90#L1522
For nodes that have connectivity to at least 1 free node, the diagonal can get filled from the left side C^T in CMC.

Thank you for the response. I'll close the issue now.
