### ISSUE TITLE
Do we want Statplot to depend onto classes defined elsewhere?

### ISSUE THREAD

**Issue by Patol75** [FluidityProject/fluidity#236]
I am just wondering if it makes sense to have Statplot using the Stat class defined in `./python/fluidity/diagnostics/fluiditytools.py`, which depends on the stat_parser class defined in `./python/fluidity_tools.py`, and the JoinStat class defined in `./python/fluidity/diagnostics/fluiditytools.py` as well? The reason for this is that all that is needed in Statplot is to be able to read through potentially multiple statfiles and display their information on a single graph. I have an attempt (attached below, function ReadData) which is working for multiple statfiles that have exactly the same fields defined (restarted checkpoint). Implementing this solution would make Statplot a standalone. Please let me know your opinion on this.

EDIT: I have created a branch with the newest version https://github.com/FluidityProject/fluidity/commit/2abc6758e0e71f33ad0adde86ecf1476ae1db028

**Comment by stephankramer** [comment]
I suggest you open a PR instead? Does it work for binary stat/detectors files? If it's very limited code duplication then it would be nice to have it stand-alone, yes - but I'm less keen if this would get any bigger.
