### ISSUE TITLE
Unable to run make makefiles on master

### ISSUE THREAD

**Issue by Cmath2** [FluidityProject/fluidity#240]
With the latest pushes to master, I am now unable to use make makefiles. 

I discovered this when merging master into my development branch, although it also occurs on a completely clean master branch for me.

Steps to recreate:
git clone https://github.com/FluidityProject/fluidity.git master
./configure --enable-debugging --enable-2d-adaptivity
make makefiles

The error I receive is:
Traceback (most recent call last):
  File "../bin/create_makefile", line 237, in <module>
    dependencies=generate_dependencies(fortran)
  File "../bin/create_makefile", line 191, in generate_dependencies
    files.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
Makefile:497: recipe for target 'makefiles' failed
make: *** [makefiles] Error 1

The error appears to occur when attempting to generate dependencies for Debug.F90

**Comment by angus-g** [comment]
Whoops! I guess that doesn't get caught in the test suite... I'll make a PR for that now.

**Comment by stephankramer** [comment]
Fixed in 8fb386db62fe

However, this should be tested for indeed, so I'll leave this open for now. @tmbgreaves: is all we need to do add an extra entry in the Jenkinsfile? I seem to recall there was a test before, that also tested whether "make makefiles" changes any of the Makefile.dependencies

**Comment by tmbgreaves** [comment]
Yes - I'll push a fix for that.

**Comment by tmbgreaves** [comment]
PR #242

**Comment by stephankramer** [comment]
Fixed and tested now
