### ISSUE TITLE
Staplot broken with Python3 merge

### ISSUE THREAD

**Issue by GNikit** [FluidityProject/fluidity#243]
Hi, I am not entirely sure if it's my system or an actual bug but I think the conversion to python 3 may have broken `statplot`.

**Comment by stephankramer** [comment]
Thanks for the heads up, this has slipped through the cracks indeed.

I've pushed a fix (e525b1d) on master that now allows me to open up the few .stat files I had lying around. Could you try as well and see if everything works for you again? It's quite possible there are more similar python3 issues still.

**Comment by Patol75** [comment]
You can also have a look at 2abc675, it is aimed to work as a stand-alone. It is still work in progress though, but I have been using it for a few months now and I have not run into any issue.

**Comment by GNikit** [comment]
Thanks for the quick fix. I'll keep my eye out for any other small bugs after the Python3 change. 
One thing that comes to mind that I had to fix in our code, FETCH2, which makes use of fluidity schemas, was diamond_validation failing on Jenkins due to non-utf-8 characters in the schemas.
Fluidity has a bunch of them in the schema files so I am actually curious how your Jenkins diamond_validation passed and ours failed given that FETCH2 and Fluidity are identical under the hood.

**Comment by GNikit** [comment]
@Patol75 thanks for the suggestion, I'll have a look but I think, mainly for stability reasons, we choose to use the master.

**Comment by stephankramer** [comment]
Good to know! I initially had issues with utf-8 in fluidity's schema as well, but after this commit, https://github.com/FluidityProject/spud/commit/b3b141dc8080f90744172065596e943648aa731e, it seems to work for us. So make sure that wherever diamond picks up its diamond/preprocess.py from (might be system installed) is up to date. Secondly make sure the schema header has the correct `encoding="UTF-8"` in the xml header. If it still doesn't work (with utf-8 in the schema) please file a bug against spud attaching the schemas, as I think we should be supporting utf-8.
