### ISSUE TITLE
Q: Passing command line arguments to PETSc

### ISSUE THREAD

**Issue by GNikit** [FluidityProject/fluidity#246]
Hi, 
I was wondering if there is a way to pass command line arguments to PETSc in fluidity that do not include setting the `PETSC_OPTIONS` env variable. 
Something along the lines of `fluidity -v1 test.flml -ksp_monitor -ksp_rtol 1e-14`.
I'm asking because I came across this line of code in fluidity's main.cpp
https://github.com/FluidityProject/fluidity/blob/e525b1db48771486a10d2a3cbdb225d5a92cf4e7/main.cpp#L85-L86

**Comment by stephankramer** [comment]
No, there isn't. That call is a little misleading as `PetscInit` is our own wrapper in main/usage.cpp around `PetscInitialize`. If you read it only `argv[0]` is passed on (i.e. the name of the executable). The trouble with petsc options is that it's very hard to separate them from our own options and they don't adhere to posix style.

We used to have something along the lines of fluidity `--petsc_opts='-ksp_monitor -ksp_rtol 1e-14'` which got removed in c2769122b8 as part of the move to new style diamond options. The argument being that we want all setup parameters in one single place (reproducibility).

You could argue for a new "global" option in the schema for this, but I'm not sure I'd see much benefit. All options that a user might want should in principle be set via the solver options in the flml. There will always be some more obscure tweaks that might be needed (gamg sub-options for instance) but an experienced user can just set those via PETSC_OPTIONS.

**Comment by GNikit** [comment]
Thanks a lot for the clarification and the commit id, they were both extremely helpful. 
I agree that having everything in a .flml is convenient, but when experimenting with solvers and/or debugging PETSc I think quickly changing options without having to launch diamond can be equally beneficial.
Again, thanks for your help, future FETCH users are grateful!
