### ISSUE TITLE
Cannot install on ubuntu 18.04 using PPA

### ISSUE THREAD

**Issue by ianthomas23** [FluidityProject/fluidity#247]
When trying to install fluidity on a clean ubuntu 18.04 installation using the PPA, there are conflicts between the versions of the various spud packages, particularly `python-spud`, meaning fluidity cannot be installed.

    > apt-add-repository ppa:fluidity-core/ppa
    > apt update
    > apt-cache madison libspud-dev
    libspud-dev |    1.1.8.1 | http://ppa.launchpad.net/fluidity-core/ppa/ubuntu bionic/main amd64 Packages
    > apt-cache madison python3-spud
    python3-spud |    1.1.8.1 | http://ppa.launchpad.net/fluidity-core/ppa/ubuntu bionic/main amd64 Packages
    > apt-cache madison python-spud
    python-spud | 1.1.7-20190802-ddd431fd-1bionic2 | http://ppa.launchpad.net/fluidity-core/ppa/ubuntu bionic/main amd64 Packages

Looking at https://launchpad.net/~fluidity-core/+archive/ubuntu/ppa/+packages, spud 1.1.8.1 does not include a `python-spud` package.

**Comment by stephankramer** [comment]
Looks like the fluidity package is out-of-date. It should no longer depend on `python-spud`. `python-spud` should indeed conflict with `python3-spud` and it should be using `python3-spud`. @tmbgreaves: did you have a more up-to-date debian/control than what is in master, or shall I fix it there?

**Comment by tmbgreaves** [comment]
Good catch, thank you @ianthomas23 . @stephankramer master is the latest version; I'll update there and rebuild the package. I need to do a .17 release for Python3 in any case so will sort both of those out today -- watch this space :-)

**Comment by tmbgreaves** [comment]
This is a slightly bigger job than expected - needs a more general overhaul of the control file (and dockerfiles). I'll push a bugfix to master for all of that and aim to rebuild the package this afternoon.

**Comment by tmbgreaves** [comment]
Running some test package builds now and hoping to push a new package in the next half hour or so.

**Comment by tmbgreaves** [comment]
Changes PR'ed as #248

**Comment by tmbgreaves** [comment]
Building: https://launchpad.net/~fluidity-core/+archive/ubuntu/ppa/+build/18141356

**Comment by tmbgreaves** [comment]
Manual build breaks (which I should have thought of...). Fixing..

**Comment by tmbgreaves** [comment]
Packages built; running a test install in a container.

**Comment by tmbgreaves** [comment]
All done - merged PR.

**Comment by ianthomas23** [comment]
I can confirm that this now works OK for me. Thanks for fixing it!
