### ISSUE TITLE
Unwanted which print in make clean-test 

### ISSUE THREAD

**Issue by Patol75** [FluidityProject/fluidity#249]
I am running into an issue when I execute make clean. Particularly, make clean-test is the one raising this issue, at this line `@cd tests; PYTHONPATH=../python ../tools/testharness.py --clean >/dev/null`. It yields
``
which: no fluidity in (/home/157/td5646/fluidity/bin:/scratch/xd2/ahg157/modules/gmsh/2.16.0/bin:/scratch/xd2/ahg157/modules/cmake/3.15.5/bin:/apps/openmpi/wrapper/fortran:/apps/openmpi/wrapper:/apps/openmpi/4.0.1/bin:/apps/vtk/8.2.0/bin:/apps/netcdf/4.7.1/bin:/apps/udunits/2.2.26/bin:/apps/python3/3.7.4/bin:/apps/hdf5/1.10.5p/bin:/home/157/td5646/.local/bin:/home/157/td5646/bin:/opt/bin:/opt/Modules/v4.3.0/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/default/bin)
which: no flredecomp in (/home/157/td5646/fluidity/bin:/scratch/xd2/ahg157/modules/gmsh/2.16.0/bin:/scratch/xd2/ahg157/modules/cmake/3.15.5/bin:/apps/openmpi/wrapper/fortran:/apps/openmpi/wrapper:/apps/openmpi/4.0.1/bin:/apps/vtk/8.2.0/bin:/apps/netcdf/4.7.1/bin:/apps/udunits/2.2.26/bin:/apps/python3/3.7.4/bin:/apps/hdf5/1.10.5p/bin:/home/157/td5646/.local/bin:/home/157/td5646/bin:/opt/bin:/opt/Modules/v4.3.0/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/default/bin)
``

The system is running CentOS 8:
`[td5646@gadi-login-04 tests]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 8.0.1905 (Core) 
Release:	8.0.1905
Codename:	Core`

By comparison, no issue occurs locally on Ubuntu 18.04
`thomas@tristan:~/Softwares/petsc-3.12.2$ lsb_release -a                                                                                                                                  
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic`

Does anyone have an idea why this command in particular is raising these errors? Any help appreciated.

**Comment by stephankramer** [comment]
Hm, that's odd. It shouldn't go into the bit that runs `which fluidity` (lines 530-533) when cleaning. Have you tried running it under pdb to see where it hangs, i.e:
```
   cd tests
   PYTHONPATH=../python python3 -mpdb ../tools/testharness.py --clean
```
press "ctrl-c" when it hangs and use `bt` to look at the backtrace. In general our `make clean-test` is very heavy on disk access, so if you have a slow shared drive (Lustre) it may take quite a while.

**Comment by angus-g** [comment]
Maybe this issue should be changed to refer to the `which fluidity` part — the hang itself is an intermittent gadi-specific thing, that I believe is being investigated.

**Comment by Patol75** [comment]
Thank you to the two of you.

I think @angus-g is right in terms of the hang, it does not occur anymore.

For what comes to the which print, I was able to trace it back to fluidity/python/fluidity/regressiontest.py where the TestProblem class has a clean method which is used in the clean method of the TestHarness class in testharness.py. This which print only occurs for three directories, the only three directories which are not in fluidity/tests but rather in fluidity/examples: restratification_after_oodc, tides_in_the_Mediterranean_Sea and stokes_square_convection. More specifically, it is triggered by this line `ret = os.system("make clean")` and occurs before the echo statement of the Makefile clean instruction prints.

**Comment by stephankramer** [comment]
Ok, so this probably comes from the envcheck.mk modules in these examples. Try sticking a `2>&1` in the two lines that use which (TESTBINFLUIDITY and TESTBINFLREDECOMP) similar to how it's done in the first line.

**Comment by Patol75** [comment]
That fixes the which print, thank you. Would you mind explaining what it actually does? Not too familiar with Makefile in general.

**Comment by angus-g** [comment]
`2>&1` forwards `stderr` to `stdout` (it's actually a shell thing, not make-specific). `stdout` was already forwarded to the black hole `/dev/null`, so after that addition, both output streams get silenced.
