### ISSUE TITLE
stat2csv broken with python3

### ISSUE THREAD

**Issue by gnikit** [FluidityProject/fluidity#251]
Hi I just noticed that the stat2csv tool broke when the the change to Python 3 occured.
I used a quick fix by assigning `labels = list(labels)` in stat2csv.py line 153, although you might want to implement a more robust fix for master.

**Comment by Patol75** [comment]
From this [paragraph](https://docs.python.org/3/tutorial/datastructures.html#dictionaries), obtaining a list of keys contained in a dictionary is simply performed by calling list() onto the dictionary object. Therefore, at line 134, you could replace `labels = data.keys()` by `labels = list(data)`.
