### ISSUE TITLE
fluidity-dev not working on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by mohamedbalaha** [FluidityProject/fluidity#264]
Hi there

I am trying to install FLUIDITY on a fresh ubuntu 16.04, but for some reason the "sudo apt-get install fluidity-dev" command doesnt work, it used to work before, so I was wondering did you update something in there that no longer works on ubuntu 16.04?

The error that I get is:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fluidity-dev : Depends: python3-meshio but it is not installable
E: Unable to correct problems, you have held broken packages.

Thanks in advance.

**Comment by GNikit** [comment]
Have you tried doing `sudo apt install fluidity-dev-python3`?
Also, FYI python 2 is not officially supported https://github.com/FluidityProject/fluidity/releases/tag/4.1.16

**Comment by mohamedbalaha** [comment]
Just tried it and unfortunately it cant be located 

The message I get:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package fluidity-dev-python3

**Comment by mohamedbalaha** [comment]
@GNikit Does this mean that it only works with ubuntu 18 now?

**Comment by GNikit** [comment]
Yeah, I just realised that `fluidity-dev-python3` is not available for xenial (16.04).
If you have the option to update to bionic (18.04) that would fix your problem.

There are some pretty hacky alternatives, like downloading the fluidity-dev locally and installing meshio through pip3, that **might work** but I would not recommend this.

**Comment by jrper** [comment]
Officially, yes ubuntu 18 is now  our earliest supported Ubuntu LTS platform. Things should also work with Bionic (Ubuntu 20.04) if you're willing to go more modern.

**Comment by mohamedbalaha** [comment]
Thanks @jrper and @GNikit
