### ISSUE TITLE
PETSc has conflict variable is_sorted with Fluidity

### ISSUE THREAD

**Issue by gnikit** [FluidityProject/fluidity#266]
So PETSc(v3.13) introduced 6 months ago an enum that contains a variable `IS_SORTED = 0` in `petscis.h`. That creates a compiler conflict with Fluidity's procedure interface `is_sorted`. Is it possible to rename the interface to `is_it_sorted` or something else to resolve the conflict?

I know that officially PETSc 3.9+ is not supported but this is the only thing preventing Fluidity master from compiling with the latest version of PETSc.

**Comment by stephankramer** [comment]
Go for it. You could also just remove the generic interface and directly call `sparsity_is_sorted` in the unittest (doesn't look like it's used anywhere else).
