### ISSUE TITLE
Intel GMSH bug...

### ISSUE THREAD

**Issue by drhodrid** [FluidityProject/fluidity#27]
Just to put this on record. Our issues with Intel and reading GMSH files has been reported. You can keep track of it here:

https://software.intel.com/en-us/forums/topic/534662

Hopefully there will be a fix soon, although our workaround seems to be fine at present.

**Comment by tmbgreaves** [comment]
A bit of issue necromancy to bring this one back to our consciousness again - I'm building with Intel 2015 now on Ubuntu LTS and hitting a lot of GMSH read errors in tests, viz:

http://buildbot.ese.ic.ac.uk:8080/builders/centos6-intel2015-standard/builds/18/steps/shell_4/logs/stdio

(search for 'Error: cannot find '$Nodes' in GMSH mesh file')

Should this now be able to be fixed and this issue properly buried?

**Comment by drhodrid** [comment]
Hi Tim,

What is the exact version of intel that you are using?

Rhod

On 17 Feb 2016, at 03:00, Tim Greaves <notifications@github.com<mailto:notifications@github.com>> wrote:


A bit of issue necromancy to bring this one back to our consciousness again - I'm building with Intel 2015 now on Ubuntu LTS and hitting a lot of GMSH read errors in tests, viz:

http://buildbot.ese.ic.ac.uk:8080/builders/centos6-intel2015-standard/builds/18/steps/shell_4/logs/stdio

(search for 'Error: cannot find '$Nodes' in GMSH mesh file')

Should this now be able to be fixed and this issue properly buried?

**Comment by tmbgreaves** [comment]
[fluidity@8eca1af227d2 fluidity]$ ifort --version
ifort (IFORT) 15.0.4 20150805
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.
[fluidity@8eca1af227d2 fluidity]$ 

Very easy to update as every buildbot run installs afresh - let me know what we need here!

**Comment by jrper** [comment]
Did we ever get anywhere with this (the Intel advancing IO issues). As part of #96 we're doing more testing on intel and it's getting annoyingly difficult to tell the wood from the trees over the remaining 100 Intel test failures.

**Comment by jrper** [comment]
See pull request #99 for an attempt to deal with guessing what needs to be done at configure time by testing using a version of Ben's minimal example.

**Comment by jrper** [comment]
#99 seems to have fixed this on our intel builds, so I'm closing this for now. If anyone still has problems then feel free to reopen this.
