### ISSUE TITLE
Error while make

### ISSUE THREAD

**Issue by AkhilAkkapelli** [FluidityProject/fluidity#290]
Error was: 
./lib/libfluidity.a(Mba2d_Integration.o): In function `__mba2d_integration_MOD_adapt_mesh_mba2d':
Mba2d_Integration.F90:(.text+0x1f8d): undefined reference to `__mba2d_module_MOD_mbanodal'
./lib/libfluidity.a(Mba_adapt.o): In function `__mba_adapt_module_MOD_mba_adapt':
Mba_adapt.F90:(.text+0x3738): undefined reference to `__mba2d_module_MOD_mbanodal'
collect2: error: ld returned 1 exit status
----
Sorry, I am new to fluidity, Can someone tell me why am I getting this error?

**Comment by Patol75** [comment]
Hey, would you mind providing the command you ran to get this output?

**Comment by AkhilAkkapelli** [comment]
I tried with "--enable-sam " but it gave me an error: "Could not link with Zoltan library". So I tried configuring unconfigured packages with command "sudo dpkg --configure -a;sudo apt-get update" and fixed missing dependencies with command "sudo apt-get -f install". The next configure worked fine without any errors. Thank you for your responses.
