### ISSUE TITLE
Support for GMSH v4

### ISSUE THREAD

**Issue by tmbgreaves** [FluidityProject/fluidity#310]
With testing starting on Focal, the system GMSH version is now v.4 which falls foul of the check at femtools/Read_GMSH.F90:313 .

How straightforward would it be to update this to support recent GMSH?

**Comment by Patol75** [comment]
@angus-g has potentially done most of the work already. See #235.

**Comment by tmbgreaves** [comment]
Fantastic, thanks @Patol75
