### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by tmbgreaves** [FluidityProject/fluidity#312]
https://github.com/github/renaming

As this will need branches/PRs to be updated, I propose that we set a date for the switchover so the developer community is aware the change is pending and can update accordingly. As a suggestion, how would people feel about a date in around one month, aiming for a midweek switchover on 26th May?

**Comment by tmbgreaves** [comment]
@stephankramer @jrper @drhodrid - Any thoughts on whether 26th May would be a reasonable target date for a renaming?

**Comment by stephankramer** [comment]
Thanks Tim. This sounds fine to me

**Comment by tmbgreaves** [comment]
With no recently-active PRs open at the moment I think we're in good shape for this switch on Wednesday - if anyone has any last minute requests for postponement please speak now!

**Comment by gnikit** [comment]
Out of curiosity what will happen to PRs in Fluidity or repos that depend on Fluidity when the renaming happens. Is it as simple as rebasing and updating the branch?

**Comment by tmbgreaves** [comment]
PRs should be fairly straightforward - if you 'edit' the name in the github web interface, you get a drop-down option to change the base branch. I think most dependent repos which hook into Fluidity will hook into the default branch rather than the master branch, and the default will get switched to 'main' so that *should* be fairly seamless. If there's an upstream, I guess it will probably need updating, but that again is reasonably straightforward from command line.

**Comment by gnikit** [comment]
Thanks @tmbgreaves for the explanation, that's great!

**Comment by tmbgreaves** [comment]
Changeover complete.
