### ISSUE TITLE
PETSc did not converge for matrix solve

### ISSUE THREAD

**Issue by LeiZ2** [FluidityProject/fluidity#322]
A bit background: I am a Fluidity user. I use Fluidity to run subduction (geodynamic) models based on Garel et al., 2014. The error is met when I am running parallel with 30 cores with Fluidity 4.1.15.

fluidity.err message:
> WARNING: Failed to converge.
>  PETSc did not converge for matrix solve of: MaterialVolumeFraction
>  Reason for non-convergence is undefined:          -11
>  Number of iterations:            0
>  Sending signal to dump and finish
>  Dumping matrix equation in file called matrixdump

Diagnose:
I ran “petsc_readnsolve subduction.flml MaterialVolumeFraction -l” and got the following messge:
> For multi-material/phase you need to provide the material_phase and the field name, e.g. SolidPhase::Pressure
> *** ERROR ***
> Error message: Missing material_phase name

I am sure the material_phase name is already there. So is the field name. I have attcached the list of material_phase name and field name defined in the *.flml.
![image](https://user-images.githubusercontent.com/33322857/119157365-04c1f400-ba4d-11eb-9d7f-7ddea3e196a4.png)

Solution that used to "fix" the problem (not sure if that's fixed, there is just no error message any more...)
This is a quite common error message that I met running this series of models. I have some experience handling this before when the simulation was less complex. 
Method 1) Produce a mesh with finer resolution by turning on <output_adapted_mesh/> in a serial running first. Then, use this adapted mesh to run in parallel. This method usually works better than Method 2.
Method 2) Alternatively, reduce the total cores used in parallel running, eg. from 40 cores reduce to 10 cores. This usually delays the error message and sometimes "kill" the error.

But this time when I increased the complexity of the model, both methods failed. I tried Method 1, the quality of adapted mesh was just too poor to make a difference. The mesh produced by serial running stopped adapting somehow and there was no error message about it. The first_timestep_mesh is attached.
![image](https://user-images.githubusercontent.com/33322857/119155695-59646f80-ba4b-11eb-98ee-c14c36472c7a.png)

Then I tried Method 2, i.e. reducing the CPU cores from 40 to 10. It just delayed the error message for some output timesteps, and the output frequency was not ideal.

My questions are:
-could someone help me diagnose the error message? In what circumstances would the name of material_phase or the fields be missed during parallel running?
-if method 1/2 somehow makes sense? any other possilbe solutions? 

P.S. error and log files are attached below.
[err and log.zip](https://github.com/FluidityProject/fluidity/files/6523524/err.and.log.zip)

**Comment by LeiZ2** [comment]
@gnikit Hi, many thanks for your instant reply. I have taken your advice and tried to debug with petsc_readnsolve following the procedure from Fluidity mannual, i.e. I did not rerun the model. But it seems that I did not solve the problem.
> ![image](https://user-images.githubusercontent.com/33322857/119339797-89995180-bc89-11eb-8759-9dc0dfa14d12.png)

Changes made in *.flml:
I have tried to change the factorization_package from "mumps" to "umfpack" and "petsc" (the only two other choices available if preconditioner is "lu"). I also tested a different preconditioner "bjacobi", "ksp", "mg", "asm"  instead of "lu". But I still have the following error message after running “petsc_readnsolve subduction.flml MaterialVolumeFraction -l”.
> For multi-material/phase you need to provide the material_phase and the field name, e.g. SolidPhase::Pressure
> *** ERROR ***
> Error message: Missing material_phase name

I have attached a list of documents you may need to replicate. Let me know if you need any other files. 

list of files in [replicate_files.zip](https://github.com/FluidityProject/fluidity/files/6532090/replicate_files.zip):
subduction.flml (note that there are three material_phase: Normal, Weak and Craton)
matrixdump.info
matrixdump
fluidity.err
fluidity.log

**Comment by gnikit** [comment]
From the looks of it you are using an older (Python 2) version of Fluidity which we don't develop anymore since Python 2 has been deprecated in later Ubuntu releases see Fluidity release [4.1.16](https://github.com/FluidityProject/fluidity/releases/tag/4.1.16). All that is to say that I don't think I will be able to replicate the issue locally.

That being said could I ask you to 

```sh
export PETSC_OPTIONS="-ksp_error_if_not_converged"
```

and then run `petsc_readnsolve` for `MaterialVolumeFraction`. Could I also ask you to set your solver to `gmres` with `mg` or `ilu` as the preconditioner.

Then post the error message that PETSc throws in your .log/.err file (not sure where it will be placed)

**Comment by LeiZ2** [comment]
Hi @gnikit, many thanks for following this issue. It seems the command `PETSC_OPTIONS="-ksp_error_if_not_converged"` is not available in the server where I run fluidity/4.1.15. I have attached a screenshot of the module list and commands executable started with petsc for you to diagnose.
![image](https://user-images.githubusercontent.com/33322857/119782330-f9931c00-bec3-11eb-81d0-143ec7e061be.png)

Anyway, I tried to input `export PETSC_OPTIONS="-ksp_error_if_not_converged"` and then run `petsc_readnsolve` for `MaterialVolumeFraction `with the solver and two preconditioners you mentioned separately. The petsc_readnsolve.err messages reported are both still: 

> For multi-material/phase you need to provide the material_phase and the field name, e.g. SolidPhase::Pressure
> *** ERROR ***
> Error message: Missing material_phase name

You mentioned the fluidity version. Does that mean setup in the flml file is significantly different in the later version of fluidity? If we, unfortunately, do not find an effective solution for the error, do you think that it is necessary for me to build the latest version of fluidity and rebuild flml with diamond therein?
