### ISSUE TITLE
Unable to derive higher order hex mesh from linear

### ISSUE THREAD

**Issue by markgoffin** [FluidityProject/fluidity#38]
I looked into the question that was raised on the old launchpad site. It seems to be an issue when attempting to create a second order hex mesh from a first order mesh. Comments in the code tend to refer to tets, hexes were potentially overlooked when writing these routines.

**Comment by jrper** [comment]
Hi Mark, I suspect Michael may want to comment, but as I understand it, quads and hexes are about to move from being deprecated into being unsupported, while progress is made on moving to using the PETSc DMplex data structures. I'm not sure if this is something you want to work on, but if it is, you may need to be careful your work isn't wasted.

**Comment by markgoffin** [comment]
Ok thanks James. I had a quick look at it yesterday but couldn't see anything quick and easy to fix (not to say it isn't). I probably won't look any further into it, but will post if I do find a quick fix.
