### ISSUE TITLE
NetCDF reader not keeping up with CF convention changes.

### ISSUE THREAD

**Issue by slmouradian** [FluidityProject/fluidity#39]
At the moment, the NetCDF reader is trying to second-guess netcdf dimensions and variable names.  The newest GEBCO bathymetry follows convention COARDS, CF1.5, a CF convention not currently supported and therefore can not be read unless the user hacks the netcdf file in a very specific way.

A more appropriate solution would be to have the user inform Fluidity of the netcdf variables in Diamond. A quicker, less appropriate solution is to implement support for COARDS CF 1.5.

Relevant file: bathymetry/NetCDF_reader.cpp

**Comment by tmbgreaves** [comment]
Closing this, as three years on there seems not to have been interest in fixing or critical need for a fix.
