### ISSUE TITLE
Configure query relating to adjoint...

### ISSUE THREAD

**Issue by drhodrid** [FluidityProject/fluidity#56]
Could somebody please explain to me why, on current fluidity master, if I specify the following configure and build command:

./configure --enable-2d-adaptivity --enable-debugging LDFLAGS="-L/data/rhodrid/Packages/Zoltan/Zoltan_v3.81/build/lib -I/data/rhodrid/Packages/Zoltan/Zoltan_v3.81/build/include" && make clean && make

My system finds zoltan .mod files (v3.81) fine. However, if I make the following subtle modification (i.e. --with-adjoint=no):

./configure --with-adjoint=no --enable-2d-adaptivity --enable-debugging LDFLAGS="-L/data/rhodrid/Packages/Zoltan/Zoltan_v3.81/build/lib -I/data/rhodrid/Packag/Zoltan/Zoltan_v3.81/build/include" && make clean && make

It fails to find the zoltan .mod files, with the following error...

Halos_Derivation.F90:919.8:
    use zoltan
       1
Fatal Error: Can't open module file 'zoltan.mod' for reading at (1): No such file or directory

Could somebody that better understands configure please explain this to me? I'm clearly missing something!!

Best wishes,

Rhod

With adjoint log here: https://www.dropbox.com/s/lr7nxvh56s08nkm/config_with_adjoint.txt?dl=0
Without adjoint here: https://www.dropbox.com/s/z46310u30vvlio1/config_no_adjoint.txt?dl=0

**Comment by jrper** [comment]
Hi Rhod,
your principle problem is that your call to configure abuses environment variables. LDFLAGS is meant to be used by the linker (theoretically ld, but in fact we link using the C++ compiler.), which joins all the compiled object files and library information together into a single file. Generally include information only needs to be passed to the compiler(s), using e.g.. CPPFLAS and FCFLAGS. So these ought to be set with the "-I" part of the call above, while you can leave the "-L" part where it is.

**Comment by drhodrid** [comment]
Thanks Percy... and apologies for my abuse of the variables ;-) You'll be pleased to know that by adding the zoltan include path to FCGLAGS and CPPFLAGS, as you suggested, all works fine. I'll close the ticket.

Thanks again.

R
