### ISSUE TITLE
Change default fluidity build to --with-adjoint=no

### ISSUE THREAD

**Issue by drhodrid** [FluidityProject/fluidity#57]
Hi all,

Would there be any objection to the default build setup becoming --with-adjoint=no? At present, if you do not have libadjoint installed, you get hundreds of spurious warnings during the fluidity build (missing include directories etc...). As fluidity users shouldn't really be expected to install libadjoint, my preference would be to change the build default, such that the adjoint side of things is only built when requested.

How many people are actually using the adjoint functionality inside fluidity? Is this something that we want to support in the long-term or has everybody now migrated to libadjoint, firedrake etc...? 

Rhod

**Comment by funsim** [comment]
Im not using it anymore, and would not object to having it deactivated by
default

2015-05-22 4:58 GMT+02:00 Rhodri Davies <notifications@github.com>:

> Hi all,
>
> Would there be any objection to the default build setup becoming
> --with-adjoint=no? At present, if you do not have libadjoint installed, you
> get hundreds of spurious warnings during the fluidity build (missing
> include directories etc...). As fluidity users shouldn't really be expected
> to install libadjoint, my preference would be to change the build default,
> such that the adjoint side of things is only built when requested.
>
> How many people are actually using the adjoint functionality inside
> fluidity? Is this something that we want to support in the long-term or has
> everybody now migrated to libadjoint, firedrake etc...?
>
> Rhod
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FluidityProject/fluidity/issues/57>.
>



-- 
Simon Funke

Center for Biomedical Computing
Simula Research Laboratory
Oslo, Norway
simon@simula.no

**Comment by slmouradian** [comment]
@funsim (and @pefrarrell): There's been talk of having libadjoint stripped from Fluidity, as realistically it will not reach a usable stage any time soon. Are there any objections to this?

**Comment by funsim** [comment]
No objections from my side

**Comment by jrper** [comment]
The striping of libadjoint support was dealt with in @slmouradian's pull request #61, which reached master in 73e29a0.
