### ISSUE TITLE
Proposals for a .gitignore file structure

### ISSUE THREAD

**Issue by jrper** [FluidityProject/fluidity#64]
Following recent discussion during a pull request, the question of adding a .gitignore file system to the repository has come up. While this might be convenient for developers (depending on their workflow choices) there are obvious risks of encouraging lazy behaviour and bad housekeeping through through a poorly formatted selection. As such I propose the following as a starting point for discussion

root .gitignore file

```
### Various OS files

## OS X related
.DS_Store
.AppleDouble
.LSOverride
._*

## Linux related
*~

## Emacs files
# -*- mode: gitignore; -*-
\#*\#
/.emacs.desktop
/.emacs.desktop.lock
*.elc
auto-save-list
tramp
.\#*


 ### Python related files
 # Byte-compiled / optimized / DLL files
 __pycache__/
*.py[cod]

# C extensions
*.o
*.so

# Fortran extensions
*.mod

### directories
bin/
include/*.*
lib/
```

manual/.gitignore file

```
## Core latex/pdflatex auxiliary files:
*.aux
*.lof
*.log
*.lot
*.fls
*.out
*.toc

## Intermediate documents:
*.dvi


## Bibliography auxiliary files (bibtex/biblatex/biber):
*.bbl
*.bcf
*.blg
*-blx.aux
*-blx.bib
*.brf
*.run.xml


 # makeidx
*.idx
*.ilg
*.ind
*.ist
```

tests/.gitignore file

```
#temporary files created for tests
*.msh
```

**Comment by fmilthaler** [comment]
```
## Intermediate documents:
*.dvi
```
add `*.ps` to that in manual/.gitignore file.
