### ISSUE TITLE
No tests for project_to_continuous

### ISSUE THREAD

**Issue by stephankramer** [FluidityProject/fluidity#76]
This tool does not seem to be tested. If it's not tested it can break any commit - or be removed if it happens to be in someone's way.

**Comment by jrper** [comment]
As per the discussion in the dev meeting, a number of other binaries from the tools folder also appear untested:

Checkmesh
Differentiate_Vtu
Meshconv
Probe_vtu
Streamfunction_2D
Supermesh_Difference
Vtu_Bins
fldiagnostics
unifiedmesh
visualise_elements
vtkdiagnostic
vtu2gmsh

**Comment by slmouradian** [comment]
I'll volunteer for the last three: visualise_elements, vtkdiagnostic and vtu2gmsh.

**Comment by slmouradian** [comment]
Tests created for
- vtu2gmsh: 9c59e272c1298b21bd37b8b73e29e18cd8af03aa
- vtkdiagnostic: 48b6a4a71e81c2fc922f978da845c1b23dfd70a9
- visualise_elements: ce7bbb197f9e68121251329b0d20e57173cd511c

**Comment by jrper** [comment]
Tests for checkmesh, differentiate_Vtu, meshconv, probe_vtu added. Note that the last three all have intesting limits to their functionality which might be worth revisiting.
