### ISSUE TITLE
Schema syntax error

### ISSUE THREAD

**Issue by stevendargaville** [FluidityProject/fluidity#78]
I'm getting an error when using master, only when trying to build the schema, namely:

"schemas/prognostic_field_options.rnc:981:22: error: syntax error"

The only recent modification I can see was by James a few days ago in commit b1c41e78d4c27f8d117f7ca26a15d3f514aab89d. Are you seeing this same problem James?

**Comment by cianwilson** [comment]
It looks like spud-preprocess wasn't run before merging - only rnc (no rng) files changed in that merge.  And if it is, the rnc file changes deleted an open { that renders the schema invalid.

**Comment by jrper** [comment]
Indeed. Entirely my fault and the result of adding documentation to someone else's work. No good deed goes unpunished.
