### ISSUE TITLE
Unittest build fails with Intel 2015 compiler

### ISSUE THREAD

**Issue by tmbgreaves** [FluidityProject/fluidity#91]
Building on Ubuntu 14.04 with Intel 2015 compilers and running 'make unittest', the femtools tests fail to build test_find_node_ownership_af.F90 with error as below. Similar errors occur with _if.F90, and _rtree.F90.

I have a built container which I can make available via private dockerhub repository for testing this; contact me directly if you need access.

Error is:

mpif90 -I../../include -vec-report=0 -DHAVE_NUMPY -I/usr/lib64/python2.6/site-packages/numpy/core/include -extend_source -O3 -ip -xHost -I/usr/include -I/usr/include -I/usr/include -I/opt/intel/impi/5.0.3.049/intel64/include -I/opt/intel//impi/5.0.3.049/intel64/include -Iinclude/ -r8 -I/usr/include/vtk -I/usr/include/python2.6 -DHAVE_NUMPY -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include -I/usr/include -I/usr/include -I/opt/intel/impi/5.0.3.049/intel64/include -I/opt/intel//impi/5.0.3.049/intel64/include -Iinclude/ -DHAVE_PETSC  -I/usr/include/vtk -DHAVE_VTK=1 -DHAVE_VTK=1 -I../ -c test_find_node_ownership_af.F90
ifort: command line remark #10010: option '-vec-report=0' is deprecated and will be removed in a future release. See '-help deprecated'
test_find_node_ownership_af.F90(41): error #6450: This name has already been used as an external module name.   [NODE_OWNERSHIP]
  integer, dimension(:), allocatable :: l_coords, node_ownership
--------------------------------------------------^
test_find_node_ownership_af.F90(48): error #6450: This name has already been used as an external module name.   [NODE_OWNERSHIP]
  allocate(node_ownership(node_count(positions2)))
-----------^
test_find_node_ownership_af.F90(49): error #6450: This name has already been used as an external module name.   [NODE_OWNERSHIP]
  call find_node_ownership_af(positions1, positions2, node_ownership)
------------------------------------------------------^
test_find_node_ownership_af.F90(51): error #6337: This is not a valid lvalue or rvalue.   [NODE_OWNERSHIP]
  call report_test("[All node owners found]", any(node_ownership < 0), .false., "Not all node owners found")
--------------------------------------------------^
test_find_node_ownership_af.F90(51): error #6361: An array-valued argument is required in this context.   [ANY]
  call report_test("[All node owners found]", any(node_ownership < 0), .false., "Not all node owners found")
-----------------------------------------------------------------^
test_find_node_ownership_af.F90(53): error #6337: This is not a valid lvalue or rvalue.   [NODE_OWNERSHIP]
  call report_test("[Correct map size]", size(node_ownership) /= node_count(positions2), .false., "Incorrect map size")
----------------------------------------------^
test_find_node_ownership_af.F90(53): error #6361: An array-valued argument is required in this context.   [SIZE]
  call report_test("[Correct map size]", size(node_ownership) /= node_count(positions2), .false., "Incorrect map size")
----------------------------------------------^
test_find_node_ownership_af.F90(56): error #6450: This name has already been used as an external module name.   [NODE_OWNERSHIP]
    allocate(l_coords(ele_loc(positions1, node_ownership(i))))
------------------------------------------^
test_find_node_ownership_af.F90(56): error #6284: There is no matching specific function for this generic function reference.   [ELE_LOC]
    allocate(l_coords(ele_loc(positions1, node_ownership(i))))
----------------------^
test_find_node_ownership_af.F90(56): error #6385: The highest data type rank permitted is INTEGER(KIND=8).   [ELE_LOC]
    allocate(l_coords(ele_loc(positions1, node_ownership(i))))
----------------------^
test_find_node_ownership_af.F90(57): error #6450: This name has already been used as an external module name.   [NODE_OWNERSHIP]
    l_coords = local_coords(positions1, node_ownership(i), node_val(positions2, i))
----------------------------------------^
test_find_node_ownership_af.F90(57): error #6284: There is no matching specific function for this generic function reference.   [LOCAL_COORDS]
    l_coords = local_coords(positions1, node_ownership(i), node_val(positions2, i))
---------------^
test_find_node_ownership_af.F90(66): error #6450: This name has already been used as an external module name.   [NODE_OWNERSHIP]
  deallocate(node_ownership)
-------------^
compilation aborted for test_find_node_ownership_af.F90 (code 1)
make: *** [test_find_node_ownership_af.o] Error 1
rm test_find_node_ownership_af_main.o
[fluidity@7f0c51fa0551 tests]$

**Comment by stephankramer** [comment]
I'm not entirely sure whether Intel is correct, but it is complaining about the fact that the local variable `node_ownership` has the same name as the module `node_ownership`. Could you try to simply search and replace all `node_ownership` in that test_find_node_ownership_af.F90 file with `nodeownership`, *except* in the line `use node_ownership` at the top?

**Comment by tmbgreaves** [comment]
Thanks Stephan - that builds cleanly; I'll run it through the make unittest to check no other gremlins fall out and if so will push that fix.

**Comment by tmbgreaves** [comment]
All looking good so pushed to master.
