### ISSUE TITLE
Internal compiler error building parameterisation unittests with Intel 2015

### ISSUE THREAD

**Issue by tmbgreaves** [FluidityProject/fluidity#92]
When running 'make unittest' on a build with Intel 2015 compilers, an internal compiler error is thrown whilst building parameterisation/tests/test_inner_tensor_product.F90, as per the error below.

I have a built container in a private dockerhub repository which I can make available to developers working on resolving this bug; let me know if you need access.

[fluidity@7f0c51fa0551 tests]$ make
mpicxx -I../../include -I/usr/include/vtk -I/usr/include/python2.6 -DHAVE_NUMPY -I/usr/lib64/python2.6/site-packages/numpy/core/include -I/usr/include -I/usr/include -I/usr/include -I/opt/intel/impi/5.0.3.049/intel64/include -I/opt/intel//impi/5.0.3.049/intel64/include -Iinclude/ -DHAVE_PETSC  -I/usr/include/vtk -DHAVE_VTK=1 -DHAVE_VTK=1 -L/opt/intel/composer_xe_2015/mkl/lib/intel64/ -I/usr/include/udunits2 -I/usr/include/python2.6 -DHAVE_NUMPY -I/usr/lib64/python2.6/site-packages/numpy/core/include  -O3 -ip -xHost -I../include -I../../include  -D TESTNAME=test_tensor_inner_product_ -o test_tensor_inner_product_main.o -c test_main.cpp 
In file included from /usr/include/python2.6/pyconfig.h(6),
                 from /usr/include/python2.6/Python.h(8),
                 from ../../include/python_statec.h(5),
                 from test_main.cpp(46):
/usr/include/python2.6/pyconfig-64.h(1034): warning #47: incompatible redefinition of macro "_POSIX_C_SOURCE" (declared at line 162 of "/usr/include/features.h")
  #define _POSIX_C_SOURCE 200112L
          ^

In file included from /usr/include/python2.6/pyconfig.h(6),
                 from /usr/include/python2.6/Python.h(8),
                 from ../../include/python_statec.h(5),
                 from test_main.cpp(46):
/usr/include/python2.6/pyconfig-64.h(1043): warning #47: incompatible redefinition of macro "_XOPEN_SOURCE" (declared at line 164 of "/usr/include/features.h")
  #define _XOPEN_SOURCE 600
          ^

mpif90 -I../../include -vec-report=0 -DHAVE_NUMPY -I/usr/lib64/python2.6/site-packages/numpy/core/include -extend_source -O3 -ip -xHost -I/usr/include -I/usr/include -I/usr/include -I/opt/intel/impi/5.0.3.049/intel64/include -I/opt/intel//impi/5.0.3.049/intel64/include -Iinclude/ -r8 -I../ -c test_tensor_inner_product.F90
ifort: command line remark #10010: option '-vec-report=0' is deprecated and will be removed in a future release. See '-help deprecated'
test_tensor_inner_product.F90(50): catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for test_tensor_inner_product.F90 (code 1)
make: *** [test_tensor_inner_product.o] Error 1
rm test_tensor_inner_product_main.o
[fluidity@7f0c51fa0551 tests]$

**Comment by jrper** [comment]
Hi @tmbgreaves. I'm actually independently fighting with intel builds (on the imperial cluster) at the moment. As far as I can tell, we have two interrelated issues which contribute to ICEs on Intel:

1) The ordering of use statements. I have a pull request open which attempts to improve this, including a test (see #87 and #89)
2) The polluted namespace we get due to various low level femtools modules not being private. This is proving rather more boring to fix, but I am working on it.

**Comment by tmbgreaves** [comment]
Thanks James. I've been talking to Christian about this and he was not particularly keen to fix, suggesting Amin was the main user this was targetting. My thought was that if it's not a straightforward fix we could set this to not test on Intel, but if your pull request has the potential to fix it I'll hold for the moment and return to this once you've put your fixes in. If it's still problematic after that, I'll isolate the test to the non-Intel builds (ie, it will still be tested, but only on gcc).

I'll reassign to me to keep tabs on.

**Comment by tmbgreaves** [comment]
This does indeed appear to be fixed by James' merge. Thanks!
