### ISSUE TITLE
Make "master" a protected branch

### ISSUE THREAD

**Issue by jrper** [FluidityProject/fluidity#95]
Github now have the concept of protected branches [https://github.com/blog/2051-protected-branches-and-required-status-checks]. These are branches which automatically refuse to accept forced push commits which change the branch history. I propose we activate this for the fluidity master branch

Turning this on for the master branch would prevent the accidental overwriting of existing work with new commits (It doesn't prevent all malicious behaviour but nothing much does) and would be a useful (but orthogonal) step in the process of having a CI server always do the final push to master branch.

The biggest downside that I can see is that if we ever **need** to delete history, only someone with suitable authority could do it.

**Comment by tmbgreaves** [comment]
Very much support this - I'll reset master to 'protected'.

**Comment by tmbgreaves** [comment]
Done. I'm waiting on a contact who has implemented github pull request building in buildbot to send me his config code snippet for this; if that works as expected then I like the CI-status check option too.
